POST   http://localhost:3003/apis/visitor/login
content-type: application/json

{
    "username":"us11",
    "password": "pw11"
}

###

GET   http://localhost:3003/apis/profile/show/us11
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzMTEiLCJwYXNzd29yZCI6InB3MTEiLCJpYXQiOjE2NjYyNzg2NjgsImV4cCI6MTY2NjM4NjY2OH0.F3UP2XVtbRYG0BsO0qGg8MLLI8I1qsy5gH-DJv-ZAcA


###
POST   http://localhost:3003/apis/visitor/register
content-type: application/json

{
    "username":"us11",
    "password": "pw11",
    "role":"user",
    "address": "199 Đê La Thành ",
    "birthday": null,
    "email": "hola11@gmail",
    "fullname" :""
}

###

# Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzMTEiLCJwYXNzd29yZCI6InB3MTEiLCJpYXQiOjE2NjYyNzg2NjgsImV4cCI6MTY2NjM4NjY2OH0.F3UP2XVtbRYG0BsO0qGg8MLLI8I1qsy5gH-DJv-ZAcA
POST   http://localhost:3003/apis/film/create
content-type: application/json

{
    "filmName":"HOD",
    "genreName": "Vien tuong",
    "actorName": "Daemon"
}

###
GET http://localhost:3003/apis/homePage
###

POST   http://localhost:3003/apis/film/filter/genres
content-type: application/json

{
    "genres":["Kỳ ảo","Phiêu lưu"]
}
